src/Entity/Messagerie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vangrg\ProfanityBundle\Validator\Constraints as ProfanityAssert;
/**
 * Messagerie
 *
 * @ORM\Table(name="messagerie", indexes={@ORM\Index(name="fkIdPatient", columns={"IdPatient"}), @ORM\Index(name="fkIdExpert", columns={"IdExpert"})})
 * @ORM\Entity
 */
class Messagerie
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_message", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idMessage;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_envoi", type="datetime", nullable=false)
     */
    private $dateEnvoi;

    /**
     * @var string
     * @Assert\NotBlank(message="Message vide")
	 * @ProfanityAssert\ProfanityCheck
	 * @Assert\Length(
	 *     min=1,
	 *     max=100,
	 *     minMessage=" le message doit comporter au moins {{ limit }} caractères ",
	 *     maxMessage=" le message doit comporter au plus {{ limit }} caractères "
	 *
	 * )
	 * @ORM\Column(name="contenu", type="string", length=100)
	 */
    private $contenu;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_recep", type="datetime", nullable=false)
     */
    private $dateRecep;

    /**
     * @var int
     *
     * @ORM\Column(name="IdExpert", type="integer", nullable=false)
     */
    private $idexpert;

    /**
     * @var int
     *
     * @ORM\Column(name="IdPatient", type="integer", nullable=false)
     */
    private $idpatient;

    /**
     * @ORM\Column(type="integer")
     */
    private $IdEnv;

    /**
     * @ORM\Column(type="integer")
     */
    private $IdRec;


	/**
	 * @return int
	 */
	public function getIdMessage(): int
	{
		return $this->idMessage;
	}

	/**
	 * @param int $idMessage
	 */
	public function setIdMessage(int $idMessage): void
	{
		$this->idMessage = $idMessage;
	}

	/**
	 * @return \DateTime
	 */
	public function getDateEnvoi(): \DateTime
	{
		return $this->dateEnvoi;
	}

	/**
	 * @param \DateTime $dateEnvoi
	 */
	public function setDateEnvoi(\DateTime $dateEnvoi): void
	{
		$this->dateEnvoi = $dateEnvoi;
	}

	/**
	 * @return string
	 */
	public function getContenu(): ?string
	{
		return $this->contenu;
	}

	/**
	 * @param string $contenu
	 */
	public function setContenu(string $contenu): void
	{
		$this->contenu = $contenu;
	}

	/**
	 * @return \DateTime
	 */
	public function getDateRecep(): \DateTime
	{
		return $this->dateRecep;
	}

	/**
	 * @param \DateTime $dateRecep
	 */
	public function setDateRecep(\DateTime $dateRecep): void
	{
		$this->dateRecep = $dateRecep;
	}

	/**
	 * @return int
	 */
	public function getIdexpert(): int
	{
		return $this->idexpert;
	}

	/**
	 * @param int $idexpert
	 */
	public function setIdexpert(int $idexpert): void
	{
		$this->idexpert = $idexpert;
	}

	/**
	 * @return int
	 */
	public function getIdpatient(): int
	{
		return $this->idpatient;
	}

	/**
	 * @param int $idpatient
	 */
	public function setIdpatient(int $idpatient): void
	{
		$this->idpatient = $idpatient;
	}

    public function getIdEnv(): ?int
    {
        return $this->IdEnv;
    }

    public function setIdEnv(int $IdEnv): self
    {
        $this->IdEnv = $IdEnv;

        return $this;
    }

    public function getIdRec(): ?int
    {
        return $this->IdRec;
    }

    public function setIdRec(int $IdRec): self
    {
        $this->IdRec = $IdRec;

        return $this;
    }


}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontController extends AbstractController
{

	/**
	 * @Route("/", name="app_front")
	 */
	public function indexFront(): Response
	{
		return $this->render('front/index.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/DoctorFront", name="DoctorFront")
	 */
	public function DoctorFront(): Response
	{
		return $this->render('front/doctor-layout-1.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/Doctor2Front", name="Doctor2Front")
	 */
	public function Doctor2Front(): Response
	{
		return $this->render('front/doctor-layout-2.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/MapFront", name="MapFront")
	 */
	public function MapFront(): Response
	{
		return $this->render('front/map-grid-layout.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/Map2Front", name="Map2Front")
	 */
	public function Map2Front(): Response
	{
		return $this->render('front/map-list-layout.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/LoginFront", name="LoginFront")
	 */
	public function LoginFront(): Response
	{
		return $this->render('front/page-login.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/SignupFront", name="SignupFront")
	 */
	public function SignupFront(): Response
	{
		return $this->render('front/page-sign-up.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/singlelistingsFront", name="singlelistingsFront")
	 */
	public function singlelistingsFront(): Response
	{
		return $this->render('front/single.listings.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}


	/**
	 * @Route("/bloggridFront", name="bloggridFront")
	 */
	public function bloggridFront(): Response
	{
		return $this->render('front/blog-grid.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/bloglistFront", name="bloglistFront")
	 */
	public function bloglistFront(): Response
	{
		return $this->render('front/blog-list.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/blogclassicFront", name="blogclassicFront")
	 */
	public function blogclassicFront(): Response
	{
		return $this->render('front/blog-classic.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/blogsingleFront", name="blogsingleFront")
	 */
	public function blogsingleFront(): Response
	{
		return $this->render('front/blog-single.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/aboutusFront", name="aboutusFront")
	 */
	public function aboutusFront(): Response
	{
		return $this->render('front/page-about.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

	/**
	 * @Route("/erreurFront", name="erreurFront")
	 */
	public function erreurFront(): Response
	{
		return $this->render('front/page-404.html.twig', [
			'controller_name' => 'FrontController',
		]);
	}

}

templates/front/blog-classic.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <body>

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container">
            <ol class="breadcrumb opacity-5">
                <li><a href="#">Home</a></li>
                <li><a href="#">Blog</a></li>
                <li class="active">Classic Blog</li>
            </ol>
            <h1 class="font-weight-300">Classic Blog</h1>
        </div>
    </div>


    <div class="margin-tb-30px">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-lg-12 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/1600x800" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <div class="text-grey-2 margin-bottom-10px">Mauris fermentum porta sem, non hendrerit enim bibendum consectetur. Fusce diam est, porttitor vehicula gravida at</div>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-12 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/1600x800" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <div class="text-grey-2 margin-bottom-10px">Mauris fermentum porta sem, non hendrerit enim bibendum consectetur. Fusce diam est, porttitor vehicula gravida at</div>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-12 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/1600x800" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <div class="text-grey-2 margin-bottom-10px">Mauris fermentum porta sem, non hendrerit enim bibendum consectetur. Fusce diam est, porttitor vehicula gravida at</div>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                    </div>

                    <ul class="pagination pagination-md ">
                        <li class="page-item disabled"><a class="page-link rounded-0" href="#" tabindex="-1">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link rounded-0" href="#">Next</a></li>
                    </ul>

                </div>
                <div class="col-lg-4">

                    <div class="margin-bottom-30px">
                        <div class="padding-30px background-white border-radius-10">
                            <h4><i class="fas fa-search margin-right-10px text-main-color"></i> Search</h4>
                            <hr>
                            <div class="input-group mb-3">
                                <input type="text" value="Search..." class="form-control border-radius-0">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary text-white background-main-color border-radius-0" type="button">Search</button>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="widget widget_categories">
                        <div class="margin-bottom-30px">
                            <div class="padding-30px background-white border-radius-10">
                                <h4><i class="far fa-folder-open margin-right-10px text-main-color"></i> Categories</h4>
                                <hr>
                                <ul>
                                    <li><a href="#">Tech</a></li>
                                    <li><a href="#">Gallary</a></li>
                                    <li><a href="#">UI Design </a></li>
                                    <li><a href="#">Shop</a></li>
                                    <li><a href="#">Wordpress  </a></li>
                                    <li><a href="#">Cultur</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="widget widget_categories">
                        <div class="margin-bottom-30px">
                            <div class="padding-30px background-white border-radius-10">
                                <h4><i class="fab fa-instagram margin-right-10px text-main-color"></i> Instagram</h4>
                                <hr>
                                <div class="row">
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/400x400" alt=""></a></div>
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/400x400" alt=""></a></div>
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/400x400" alt=""></a></div>
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/400x400" alt=""></a></div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
    </body>
{% endblock %}

templates/front/blog-grid.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <body>
    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container">
            <ol class="breadcrumb opacity-5">
                <li><a href="#">Home</a></li>
                <li><a href="#">Blog</a></li>
                <li class="active">Grid Blog</li>
            </ol>
            <h1 class="font-weight-300">Grid Blog</h1>
        </div>
    </div>


    <div class="margin-tb-30px">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/450x240" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/450x240" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/450x240" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/450x240" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/450x240" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="#"><img src="http://placehold.it/450x240" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="#" class="text-main-color">News </a> ,
                                <a href="#" class="text-main-color">Articles </a>
                                <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                                <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                                <span class="text-extra-small"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                            </div>
                        </div>
                    </div>

                    <ul class="pagination pagination-md ">
                        <li class="page-item disabled"><a class="page-link rounded-0" href="#" tabindex="-1">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link rounded-0" href="#">Next</a></li>
                    </ul>

                </div>
                <div class="col-lg-4">

                    <div class="margin-bottom-30px">
                        <div class="padding-30px background-white border-radius-10">
                            <h4><i class="fas fa-search margin-right-10px text-main-color"></i> Search</h4>
                            <hr>
                            <div class="input-group mb-3">
                                <input type="text" value="Search..." class="form-control border-radius-0">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary text-white background-main-color border-radius-0" type="button">Search</button>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="widget widget_categories">
                        <div class="margin-bottom-30px">
                            <div class="padding-30px background-white border-radius-10">
                                <h4><i class="far fa-folder-open margin-right-10px text-main-color"></i> Categories</h4>
                                <hr>
                                <ul>
                                    <li><a href="#">Tech</a></li>
                                    <li><a href="#">Gallary</a></li>
                                    <li><a href="#">UI Design </a></li>
                                    <li><a href="#">Shop</a></li>
                                    <li><a href="#">Wordpress  </a></li>
                                    <li><a href="#">Cultur</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="widget widget_categories">
                        <div class="margin-bottom-30px">
                            <div class="padding-30px background-white border-radius-10">
                                <h4><i class="fab fa-instagram margin-right-10px text-main-color"></i> Instagram</h4>
                                <hr>
                                <div class="row">
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/450x400" alt=""></a></div>
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/450x400" alt=""></a></div>
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/450x400" alt=""></a></div>
                                    <div class="col-6 margin-bottom-20px"><a href="#"><img class="border-radius-10" src="http://placehold.it/450x400" alt=""></a></div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
    </body>
{% endblock %}

templates/front/page-404.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <body>

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container text-center">
            <ol class="breadcrumb opacity-5">
                <li><a href="#">Home</a></li>
                <li class="active">404 page</li>
            </ol>
        </div>
    </div>

    <div class="container margin-bottom-100px">
        <div class="text-center">
            <img src="assets/img/404.png" alt="">
            <h3 class="text-center">Page Not Fount</h3>
            <h4 class="text-center text-grey-2">Ooops! The page you are looking for, couldn't be found.</h4>

            <a href="{{ path('app_front') }}" class="btn btn-sm border-radius-30 margin-tb-15px text-white background-second-color  box-shadow padding-lr-25px margin-left-30px"><i class="fas fa-home  margin-right-7px"></i>  Go Home</a>
        </div>
    </div>

    </body>
{% endblock %}

templates/front/page-login.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <body>

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container text-center">
            <ol class="breadcrumb opacity-5">
                <li><a href="#">Home</a></li>
                <li class="active">Login</li>
            </ol>
            <h1 class="font-weight-300">Login Page</h1>
        </div>
    </div>

    <div class="container margin-bottom-100px">
        <!--======= log_in_page =======-->
        <div id="log-in" class="site-form log-in-form box-shadow border-radius-10">

            <div class="form-output">
                <form>
                    <div class="form-group label-floating">
                        <label class="control-label">Your Email</label>
                        <input class="form-control" placeholder="" type="email">
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Your Password</label>
                        <input class="form-control" placeholder="" type="password">
                    </div>

                    <div class="remember">
                        <div class="checkbox">
                            <label>
                                <input name="optionsCheckboxes" type="checkbox">
                                Remember Me
                            </label>
                        </div>
                        <a href="#" class="forgot">Forgot my Password</a>
                    </div>

                    <a href="01-home.html" class="btn btn-md btn-primary full-width">Login</a>

                    <div class="or"></div>

                    <a href="#" class="btn btn-md bg-facebook full-width btn-icon-left"><i class="fab fa-facebook margin-right-8px" aria-hidden="true"></i> Login with Facebook</a>

                    <a href="#" class="btn btn-md bg-twitter full-width btn-icon-left"><i class="fab fa-twitter margin-right-8px" aria-hidden="true"></i> Login with Twitter</a>


                    <p>Don't you have an account? <a href="page-sign-up.html">Register Now!</a> </p>
                </form>
            </div>
        </div>
        <!--======= // log_in_page =======-->

    </div>
    </body>
{% endblock %}

templates/front/pdf.html.twig
{% block body %}
    <h2 class="heading" style="text-align: center;">
        Messagerie </h2>
    <hr>



    <table class="table"  style="width:100%">
    <thead>
     <tr>
         <th style="width:20%" >Par </th>
         <th >Contenu</th>
         <th style="width:30%" >Date</th>
     </tr>
    </thead>
        <tbody>

        {% for n in nom %}
    {% for m in messag %}
        {% if m.idpatient == m.idEnv %}
x
        <tr>
        <td>{{ n.nom}} </td>
        <td>{{ m.Contenu }}</td>
        <td>{{ m.dateRecep | date('l d F - H:i') }}</td>
       </tr>

        {% else %}
            <tr>
                <td>Moi </td>
                <td>{{ m.Contenu }}</td>
                <td>{{ m.dateRecep | date('l d F - H:i') }}</td>
            </tr>
        {% endif %}
    {% endfor %}
    {% endfor %}
    </tbody>
    </table>

{% endblock %}